# Generated by Django 5.2.7 on 2025-10-12 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=12)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('goal', models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Maintain Weight', 'Maintain Weight'), ('Gain Muscle', 'Gain Muscle')], max_length=20)),
                ('activity_level', models.CharField(choices=[('Sedentary (little exercise)', 'Sedentary (little exercise)'), ('Lightly Active (1-3 days/week)', 'Lightly Active (1-3 days/week)'), ('Active (3-5 days/week)', 'Active (3-5 days/week)'), ('Very Active (6-7 days/week)', 'Very Active (6-7 days/week)')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
